# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SocialAppCleanSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialAppCleanSwift
  pod 'Alamofire'
  pod 'SwiftyJSON'

  target 'SocialAppCleanSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SocialAppCleanSwiftUITests' do
    # Pods for testing
  end

end
